import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/footer/footer";
import AppContext, { Context } from "../stateManagers/context/Context";
import FloatingMenu from "./components/floatingMenu/FloatingMenu";
import { Roboto_Mono } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

const robotoMono = Roboto_Mono({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${inter.className}`}>
        <AppContext>
          <Navbar />
          <FloatingMenu />
          {children}
          <Footer />
        </AppContext>
      </body>
    </html>
  );
}
